server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      saludo: Configuracion ConfigServer
      server:
        git:
          uri: https://github.com/ddfdesign2018/SpringConfig